# Generated by Django 3.1.1 on 2021-09-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDmscv', '0010_merge_20210415_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agradecimiento',
            name='cod_per',
            field=models.CharField(max_length=50, verbose_name='Codigo de la Persona'),
        ),
        migrations.AlterField(
            model_name='data',
            name='fecha_add',
            field=models.CharField(max_length=50, verbose_name='Fecha de registro'),
        ),
    ]
